# Generated by Django 4.2.13 on 2024-06-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='dateAdded',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='description',
            field=models.TextField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffee',
            name='isGround',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
