# Generated by Django 4.2.13 on 2024-06-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_coffee_dateadded_coffee_description_coffee_isground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='coffee',
        ),
    ]
