# Generated by Django 4.2.13 on 2024-06-14 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_brand_coffee'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='coffee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='server.coffee'),
            preserve_default=False,
        ),
    ]
