# Generated by Django 4.2.13 on 2024-06-14 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_coffee_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coffees', to='server.brand'),
            preserve_default=False,
        ),
    ]
