# Generated by Django 4.2.13 on 2024-06-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_coffee_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
